# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: harder.SkillView
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - skillview
Dependencies:
  PackageDependencies:
    - PackageIdentifier: GitHub.cli
      MinimumVersion: 2.97.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/harder/gh-skillview/releases/download/v1.0.0/skillview-windows-amd64.exe
    InstallerSha256: 34AD08714981F056164946AC01944A9409A1BAD9EF68D8449701F1CC7EEBBD50
  - Architecture: arm64
    InstallerUrl: https://github.com/harder/gh-skillview/releases/download/v1.0.0/skillview-windows-arm64.exe
    InstallerSha256: 80E77253498ECE2662738ED746961C435A856EDA0D15FF84DAA9E3E4869CAFAC
ManifestType: installer
ManifestVersion: 1.12.0
